### PR TITLE
bower install allow-root

### PR DESCRIPTION
**Pull request by tembi4-84**
--allow-root for bower installation to prevent fails inside Docker containers

### CODE REVIEW

**Comment by johndevs** [comment]
Hi @tembi4-84 , 

I updated your PR with the latest changes for master. 

If you could sign the CLA (by clicking on the _details_ link) then I can merge this into the master branch.

**Comment by tembi4-84** [comment]
Hi @johndevs, I had signed it (You have signed the CLA for devsoap/gradle-vaadin-flow
Version: 2018-09-14), but in the PR it still says "NOT signed"...

**Comment by tembi4-84** [comment]
@johndevs 
image

**Comment by johndevs** [comment]
This is strange. I'll rebase the change and see if it would make a difference.

It can also be that if you are using multiple Github accounts that somehow the signature was given with the wrong account (https://github.com/cla-assistant/cla-assistant/issues/241). In that case try to sign it again using another browser window where you haven't signed in to Github before.

**Pull request closed without merging**
